apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mad-ingress
spec:
  ingressClassName: traefik  # <--- La nouvelle faÃ§on de faire propre
  rules:
    - host: keycloak.192.168.56.10.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak-service
                port:
                  number: 8080
    - host: minio.192.168.56.10.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-service
                port:
                  number: 9001
    - host: node.192.168.56.10.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy-service
                port:
                  number: 80