apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
        command:
        - /bin/oauth2-proxy
        - --provider=keycloak-oidc
        - --client-id=mad-backend
        - --client-secret=6rWrWJRJCRiuBXSCLvhGTBllVWTD5GOt
        - --cookie-secret=V2kRX1G9630YajZL5t7WmjkePW3BSDWHOV1dIgmowws=
        - --oidc-issuer-url=http://keycloak.192.168.56.10.nip.io/realms/mad
        - --redirect-url=http://node.192.168.56.10.nip.io/oauth2/callback

        # Configuration identit√©s
        - --user-id-claim=preferred_username
        - --oidc-email-claim=email
        - --scope=openid profile email
        - --insecure-oidc-allow-unverified-email=true

        # Configuration headers
        - --pass-access-token=false
        - --set-xauthrequest=true
        - --pass-user-headers=true

        - --email-domain=*
        - --upstream=http://backend-node-service:80
        - --http-address=0.0.0.0:4180
        - --cookie-secure=false
        - --reverse-proxy=true
        - --whitelist-domain=.192.168.56.10.nip.io
        - --cookie-domain=.192.168.56.10.nip.io
        ports:
        - containerPort: 4180
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-service
spec:
  type: ClusterIP
  selector:
    app: oauth2-proxy
  ports:
    - port: 80
      targetPort: 4180